# Generated by Django 4.2.11 on 2024-03-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customuser_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
