# Generated by Django 4.2.11 on 2024-03-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtranscript',
            name='transcript',
        ),
    ]
