# Generated by Django 4.2.11 on 2024-03-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_meetingtranscript_transcript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingtranscript',
            old_name='abstract_summary',
            new_name='comprehension_report',
        ),
        migrations.RenameField(
            model_name='meetingtranscript',
            old_name='action_items',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='meetingtranscript',
            old_name='sentiment',
            new_name='next_session_blueprint',
        ),
        migrations.RenameField(
            model_name='meetingtranscript',
            old_name='key_points',
            new_name='therapy_report',
        ),
        migrations.RenameField(
            model_name='meetingtranscript',
            old_name='recommendation',
            new_name='therapy_session',
        ),
    ]
